### ISSUE TITLE
"compare with current" throws

### ISSUE THREAD

**Issue by dwelle** [arturock/vscode-gitstash#10]
System: windows 7 x64
vscode-gitstash: 1.0.1
vscode: 1.29.0 (system setup)

When clicking on the `compare with current` on a stashed file, it throws:

```
Unable to open '#0: items.js - Modified (server/)': A system error occurred (UNKNOWN: unknown error, stat '\\c:\repos\test\server\items.js').
```

**Comment by arturock** [comment]
Hi @dwelle, thanks for the report! I'll fix it as soon as I get some time

**Comment by arturock** [comment]
Hi @dwelle, sorry for the delay. Would you mind to confirm if its working for you with the new version?

**Comment by dwelle** [comment]
it does, good job :+1:
