### ISSUE TITLE
Stashes not visible with mutiple repos

### ISSUE THREAD

**Issue by sketchbuch** [arturock/vscode-gitstash#11]
My workspace contains two folders with two different repos. I can stash via the VSC menu options and verify the stash exists on the command line but vscode-gitstash doesn't show anything in the stash - for any repo. It normally does when using a Workspace with just one repo.

**Comment by Adrian-Sanchez** [comment]
Its happening to me as well when i have multiple repos in the same workspace. It would be nice if i didn't have to switch between them to get this feature to work. But when in single repo mode, its very useful

**Comment by arturock** [comment]
Hi @sketchbuch, @Adrian-Sanchez. In deed, multiple repos are currently not supported. I've been quite busy these days but recently got some time and started working on this and it's almost complete, so in some days feature will be available. I'll let you know when this is done.

**Comment by Adrian-Sanchez** [comment]
Hey thanks, it will happy coding when it’s done.

Much Appreciated!

~Adrian

**Comment by arturock** [comment]
Done. Let me know if you have any issue.
