### ISSUE TITLE
[Feature Request] Recreate untracked files

### ISSUE THREAD

**Issue by lonix1** [arturock/vscode-gitstash#15]
Right now blue (tracked) files can be individually used.

But untracked files are shown in gray with a small gray "U" icon. Would be helpful to be able to recreate those files.

**Comment by arturock** [comment]
Hi @lonix1. Thanks for the suggestion. I like the idea, so I'll add this on the coming update.

**Comment by lonix1** [comment]
Thanks @arturock

**Comment by arturock** [comment]
:slightly_smiling_face:
