### ISSUE TITLE
Undefined length property in empty work areas

### ISSUE THREAD

**Issue by danielbernard** [arturock/vscode-gitstash#16]
I noticed that the debug console prints out an error from Git Stash when it's looking at a non-repo path:
```
rejected promise not handled within 1 second: TypeError: Cannot read property 'length' of undefined
extensionHostProcess.js:730
stack trace: TypeError: Cannot read property 'length' of undefined
	at Git.<anonymous> (C:\Users\<user>\.vscode\extensions\arturock.gitstash-1.0.2\out\src\Git.js:65:50)
	at Generator.next (<anonymous>)
	at fulfilled (C:\Users\<user>\.vscode\extensions\arturock.gitstash-1.0.2\out\src\Git.js:4:58)
	at process._tickCallback (internal/process/next_tick.js:68:7)
```

I'm admittedly not super familiar with JS code, but I'm guessing it's due to there being no `else` clause in the getGitRoot function
https://github.com/arturock/vscode-gitstash/blob/82e7160e81222766cfb983dd607dea95c1bf9c8d/src/Git.ts#L74-L84

I fixed this in my local copy by simply adding a
```javascript
            else {
                this.gitRootPath = "";
            }
```
between the end of the if and the return statement.

Alternatively, changing hasGitRepository as such:
```javascript
    hasGitRepository() {
        return __awaiter(this, void 0, void 0, function* () {
            if (this.getGitRoot().length != null)
                return (yield this.getGitRoot()).length > 0;
            else
                return false
        });
    }
```
These are probably not the cleanest way to handle it, so I didn't open a pull request with the changes.

**Comment by arturock** [comment]
Hi @danielbernard. Thank you for taking a look to the source to see whats happening. I guess I'd go with your second approach as I see ok to return undefined when no repo found and let hasGitRepository handle handle that.
Currently I'm testing the next version with multi-root support, so this may be already fixed. I'll take this in count to make sure extension is handling this case correctly.
