### ISSUE TITLE
Git Stash crash with the 1.33 VS Code update

### ISSUE THREAD

**Issue by AdrianGarciaSimplr** [arturock/vscode-gitstash#19]
After the VS Code 1.33.1 update. The extension chrash with the following error:

Cannot read property 'name' of undefined.

You will not see the stash list anymore.
You get the error when open VS Code
You get the error when push the stash refresh button

**Comment by arturock** [comment]
:scream:

Thanks for reporting @AdrianGarciaSimplr! Will check it as ASAP.

**Comment by arturock** [comment]
I just updated to 1.33.1 and I haven't had any problem so far. I wonder if has to do with data on any of your open repos.
Does it fail with every git project?
OS?

**Comment by AdrianGarciaSimplr** [comment]
Yes. In my teams there some developers that use the extension and have the same problem. I will check with an empty repo to see what's happens.

**Comment by MoonStruckHorrors** [comment]
Facing the same issue with the latest version of the extension. Have two stashes in my repository.

**Comment by arturock** [comment]
Hi @AdrianGarciaSimplr @MoonStruckHorrors. Got some time to review the way stashed files were identified and fixed a couple of related bugs around it that may fix the issues you were having. Would you let me know if the new version behaves correctly on your cases?

**Comment by arturock** [comment]
Closing due inactivity. Happy to reopen if issue persists.
