### ISSUE TITLE
[Feature request] Custom file stashing

### ISSUE THREAD

**Issue by HazemAM** [arturock/vscode-gitstash#20]
This is a feature request for adding custom stashing for specific changed files.

The way this works is by adding a context menu entry for only stashing selected changes.

A similar feature is available in the GitLens extension, which I want to move away from since it has a big footprint and is filled with features I don't use.

![GitLens custom stash](https://user-images.githubusercontent.com/3602800/56470478-ceb57e80-6446-11e9-969f-e734d47f0539.png)
(Choosing "Stash Changes" in this screenshot would only stash the changes in `settings.json`, and `dashboard.controller.js` since they're selected.)

I'm currently short on time, but I would be happy to help with a PR if needed once I have some free time.

Thanks!

**Comment by arturock** [comment]
Hi @HazemAM. I'd love to have this feature too. I've been quite busy these days and the little time I've got for the extension has been for reviewing, improving and fixing the code so there's now a new version released. When I get some free time I'll see what can be done for this.

**Comment by arturock** [comment]
Finally
