### ISSUE TITLE
How to get started?

### ISSUE THREAD

**Issue by paulwasit** [arturock/vscode-gitstash#23]
I feel fairly silly but I don't know how to even start using the extension. There seems to be a list of stashes in the readme, stored under `vscode-gitstash`. But my Stashes pane is empty and I don't know where to create one. Is there a right-click that I'm missing somewhere?

![image](https://user-images.githubusercontent.com/11413829/58793154-d5aedf80-85f5-11e9-95fa-977c3a028f73.png)

Note: I can `stash` / `apply stash` files using the built-in menu but I even when I do this nothing shows up under Stashes.

![image](https://user-images.githubusercontent.com/11413829/58793274-11e24000-85f6-11e9-9d92-41dd433eb53d.png)

**Comment by arturock** [comment]
Hi @paulwasit. I've been so busy but I just released a new version that may fix your issue. The extension should work out of the box (depending on the relative depth of your repositories from the opened directories). Hope it's working for you now. Would you mind to let me know?

**Comment by arturock** [comment]
Closing due inactivity. Happy to reopen if issue still not resolved.
