### ISSUE TITLE
Support for non repo root folder stash display

### ISSUE THREAD

**Issue by wenfangcn** [arturock/vscode-gitstash#24]
Currenty, the stash display only works if the folder being opened is the project root folder, if it's not, e.g. foo-project > bar, in this case, if I open bar folder in vscode, gitstash won't work, and will throw an error when opening the folder.
![image](https://user-images.githubusercontent.com/28700378/61599160-e0324080-ac58-11e9-9fd5-eeccbad4de08.png)

**Comment by wenfangcn** [comment]
I rolled back to v1.0.2, and it works now. May relate to this [issue](https://github.com/arturock/vscode-gitstash/issues/19).

**Comment by arturock** [comment]
Hi @wenfangcn. I just released a new version with a setting to configure the search depth for git repos (with a default value to search on one sublevel). I hope this works for you. Would you let me know?

**Comment by wenfangcn** [comment]
Hi @arturock , thanks for the new setting, can the depth be negative, so it can go up folder levels to find the real repo?

**Comment by arturock** [comment]
Currently only positive values are considered, but I'll see what can I do to support this

**Comment by arturock** [comment]
Hi @wenfangcn. I just got the time to work on this. Parent directories are supported on the new version using negative values. I hope the updated feature works the way you need it. Please let me know I you have any issues.

**Comment by wenfangcn** [comment]
@arturock Thanks, bro! It automatically works now like v1.0.2 did, I didn't configure `"gitstash.advanced.repositorySearchDepth"` though, is it now automatically find the nearest repo first?

**Comment by arturock** [comment]
There was a bug when searching for the repository root directories when showing the explorer tree, introduced on the refactor for supporting multi-root, this affecting Windows machines (my box is a Linux one so sadly It wasn't happening on my machine). The fix restores the broken functionality so you don't need to change anything.

Regarding the icons. Do you have any tooltip if you position the mouse over the places where icons should be? Mostly sure, commands are correctly registered but for some reason icons cannot be located. I've got a Win7-64 VM for testing purposes and icons display correctly. Not sure if has to do with your OS, vscode version or even the home folder name (where extensions are located). Did you have the icons showing on a previous extension version?

Can you see any related info if you open the developers tools view?
Maybe something along the lines of
`refresh.svg:1 Failed to load resource: net::ERR_FILE_NOT_FOUND`
If so, could you paste one of the failed link addresses?

**Comment by wenfangcn** [comment]
Oh, I see why they didn't "show up" , my stash messages were so long that I have to scroll right to find the icons 😂 .
![image](https://user-images.githubusercontent.com/28700378/65658372-f5ad5780-e059-11e9-8785-f7d47e5d3279.png)
Can you please make the icons positioning absolute to the right border, so they can always appear when hovering? 👍

**Comment by arturock** [comment]
Thanks for the info @wenfangcn . Do you by any chance have configured `workbench.list.horizontalScrolling` to `true`? This setting controls the horizontal scrolling on trees, which affects the tree view of this extension too

**Comment by wenfangcn** [comment]
Yes, I do, but the source control section is not affected by this setting though, it's still not scrollable.
![image](https://user-images.githubusercontent.com/28700378/65742704-de3aa100-e123-11e9-9db5-96be67a967c7.png)
Can git-stash also do that? It'll be great if it works even when `workbench.list.horizontalScrolling` is true, since this setting is quite useful in some cases.

**Comment by arturock** [comment]
Unfortunately no, extension tree widgets display mode depend on that setting.

**Comment by wenfangcn** [comment]
OK, I guess I'll have to change the setting now :D, thanks anyway!

**Comment by wenfangcn** [comment]
There's a similar [vscode issue](https://github.com/microsoft/vscode/issues/68027) regarding to disable horizontal scrolling for specific lists.

**Comment by arturock** [comment]
No prob dude. Thanks your input on solving the original issue and for the vscode issue reference, if something is changed I'll most probably add a setting for it.
