### ISSUE TITLE
After adding or removing stash the (stash-)explorer doesn't update

### ISSUE THREAD

**Issue by Friksel** [arturock/vscode-gitstash#25]
First of all; great extension. Very useful and I use it a lot.
That said, when adding something to stash (either from vs code controls or using the button inside the extension itself), the stash list/explorer never updates. Not even when we open a 'stash-group'. We always have to push the refresh button inside the extension to refresh the list.

It would be nice if the module could update its list/explorer automatically when adding or removing stash. That would be less confusing and speedup the workflow.

Keep up the great work!

**Comment by arturock** [comment]
Hi @Friksel. I'm glad to know the extension is helping you! The extension has an active file watcher so the stashes explorer gets automatically updated when changes are detected on the .git directory of the loaded repositories. The watcher may not work when the system runs out of handlers on Linux and presumably on missconfigured paging files in Windows.
Are you still having those problems? Could you share your editor about info? Do you have any relevant information if you toggle the editor developer tools?

**Comment by Friksel** [comment]
Thanks for your response @arturock . Yes, I'm still having this issue. On two non-identical Windows machines and also on local development as well as development via Microsofts Remote SSH extention. I never seen it automatically refreshing. On none of those machines and configurations and none of the projects I'm running. I don't have problems using .git on other places either and I just use the stash-button of the extension to add to stash.

BTW Everything here is up to date. Using the latest VS Code (1.38.0) as well as the latest version of the extension. Also all Windows updates are up to date.

![image](https://user-images.githubusercontent.com/3089978/64636950-0e373400-d403-11e9-9206-74e1c761abce.png)

**Comment by arturock** [comment]
I'll see if loosing the watching rules can help on this. Just to be sure, can you confirm you are not getting some related notifications on the developer tools window, something like

```
log.ts:173   ERR Error: [File Watcher (C#)] terminated unexpectedly (code: 2148734720, signal: null)  ERR Error: [File Watcher (C#)] terminated unexpectedly (code: 2148734720, signal: null)
log.ts:173   ERR [File Watcher (C#)] terminated unexpectedly (code: 2148734720, signal: null)
log.ts:173   ERR Error: [File Watcher (C#)] is restarted again...
log.ts:173   ERR [File Watcher (C#)] is restarted again...
```

**Comment by Friksel** [comment]
Yes, when clicking the stash-button I get an error in the console, but it doesn't say anything about a watcher:

`log.ts:173   ERR spawn git ENOENT: Error: spawn git ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:232:19)
    at onErrorNT (internal/child_process.js:407:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)`

**Comment by arturock** [comment]
Hi @Friksel. Sorry for the late response. I just published a new version with an improved strategy to watch changes. Hope the issues you were having are now solved. Could you let me know?

**Comment by arturock** [comment]
Closing due inactivity. Happy to reopen if issue persists.

**Comment by Friksel** [comment]
@arturock Sorry for my late response. I just tested it and it's working fine now in a local environment. The stash appears when adding and disappears when popping. I couldn't test it here on a remote environment, but I'll test that when I'm working on a remote project later. I let you know if something on that part is working differently, but this seem to have solved the problem. Thanks!

**Comment by Friksel** [comment]
@arturock Just tested it with Remote SSH extension and also on ssh development it's working fine! Thanks again!

**Comment by arturock** [comment]
Thanks for rising the issue and confirming it's working for you now.
