### ISSUE TITLE
Very slow init and opening diff editor

### ISSUE THREAD

**Issue by dwelle** [arturock/vscode-gitstash#38]
After last vscode upgrade (1.40.x) I noticed slow `git` extension panel init (the list of dirty files takes a long time to load), and extremely slow (between 10-30s) opening of files in diff view (comparing old to new).

Disabling this extension fixed the perf issues.

I have ~100 stashes, but this didn't cause a problem in older versions of vscode. Running `git gc` didn't improve it at all.

I've switched to `Git lens` for git stash related work, so I mainly opened this issue for future reference if people hit similar problems.

**Comment by arturock** [comment]
Hi @dwelle. I appreciate the time you took to let it me know. By the time wasn't sure how to improve it. I've updated the code so now is possible to configure to lazy load data for cases like yours.

/cc @vladimir-fed @rposborne

**Comment by rposborne** [comment]
@arturock Thanks such much.  I am in your debt.

**Comment by arturock** [comment]
You're welcome @rposborne!
Feel free to open an issue if you find a weird behavior using the feature.
