### ISSUE TITLE
Feature request: commit message with stash

### ISSUE THREAD

**Issue by faulknermano** [arturock/vscode-gitstash#44]
I was just looking for a way to organise commits and having worked with PyCharm's Changelist, I thought that this extension would be a good candidate to implement such a feature.

It is basically a title string, and commit string associated with a stash that can be used to populate the commit message field. Or even if the commit message field is not populated automatically, at least to have access to the saved string so it can be copy-pasted.

Thanks for reading!

**Comment by arturock** [comment]
Hi @faulknermano I thought it would be good idea to support coping stash info to clipboard so I added the option through right click on tree items, however setting the message field doesn't seem to me like a feature for this extension. I hope the clipboard feature comes handy to you (note that text to set to clipboard is somehow configurable through settings).

**Comment by faulknermano** [comment]
@arturock thank you for you efforts!
