### ISSUE TITLE
If you click refresh while a stash is expanded, you can't see the files

### ISSUE THREAD

**Issue by prw56** [arturock/vscode-gitstash#56]
Initial state:
![image](https://user-images.githubusercontent.com/29357588/111202321-1ba22100-859a-11eb-8e9a-3a49ee8ea411.png)

After clicking refresh:
![image](https://user-images.githubusercontent.com/29357588/111202396-34123b80-859a-11eb-97aa-a6d69c55232d.png)

They don't go back to normal until you collapse them, and refresh again.

**Comment by arturock** [comment]
Sorry for late replying. This got fixed on v4.0.0. Feel free to open a new issue if you encounter any problem
