### ISSUE TITLE
Git stash updated to 4.0.0, "drop" feature missing.

### ISSUE THREAD

**Issue by shindepankaj** [arturock/vscode-gitstash#68]

**Comment by arturock** [comment]
Hi @shindepankaj. Thanks for reporting it. Can you give more details? I'm able drop stuff using both, the drop button (trash can) on the stashes explorer and command palette

**Comment by shindepankaj** [comment]
I didn't see any trash can icon to drop stash.
![Untitled](https://user-images.githubusercontent.com/16950033/130430000-87d9797d-9650-43f1-bcb1-2ec3557ae538.png)

**Comment by arturock** [comment]
You should see something like this on the explorer:
![image](https://user-images.githubusercontent.com/2359890/130708018-444a4fa4-43cb-4289-a5bd-2fd5834cdf93.png)
And on the command palette:
![image](https://user-images.githubusercontent.com/2359890/130708271-0fc26120-077f-4e74-83cd-23b7312024b8.png)

which OS & code version are you using?

**Comment by arturock** [comment]
Glad to know you got it solved!
