### ISSUE TITLE
Stashes disappear after clicking the "pop" icon

### ISSUE THREAD

**Issue by sbungert-mms** [arturock/vscode-gitstash#70]
V4.0.0

Something seems to have changed as popping via GUI seems to delete the stash, previously the stash was still there after popping.

**Comment by arturock** [comment]
Hi @sbungert-mms. If I understood correctly that's the expected behavior. To extract the changes from a stash without removing it from the stack you can use the  'Apply...' action (available via right click over the stash item on the tree). Would you let me know if that fixes the issue for you?

**Comment by arturock** [comment]
I thought about that before but never implemented it. I'll add it for the next release.
